import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import Ajv, { type ErrorObject, type ValidateFunction } from 'ajv';
import { describe, expect, it } from 'vitest';

import { parseCodexEvent } from '../../../src/backends/codex/jsonlParser.js';

type JsonRecord = Record<string, unknown>;

const FIXTURE_DIR = resolve('tests/fixtures/codex/0.145.0');
const SCHEMA_PATH = resolve(FIXTURE_DIR, 'codex_app_server_protocol.v2.schemas.json');
const STREAM_PATH = resolve(FIXTURE_DIR, 'exec-stream.jsonl');

const schema = JSON.parse(readFileSync(SCHEMA_PATH, 'utf8')) as {
	definitions: Record<string, unknown>;
};
const events = readFileSync(STREAM_PATH, 'utf8')
	.trim()
	.split('\n')
	.map((line) => JSON.parse(line) as JsonRecord);

const ajv = new Ajv({ allErrors: true, strict: false, validateFormats: false });

function validatorFor(definition: string): ValidateFunction {
	return ajv.compile({
		$ref: `#/definitions/${definition}`,
		definitions: schema.definitions,
	});
}

const validateThreadItem = validatorFor('ThreadItem');
const validateUsage = validatorFor('TokenUsageBreakdown');

function formatErrors(errors: ErrorObject[] | null | undefined): string {
	return (
		errors
			?.map((error) => `${error.instancePath || '/'} ${error.message ?? 'is invalid'}`)
			.join('\n') ?? 'unknown schema validation error'
	);
}

function expectSchemaMatch(validate: ValidateFunction, value: unknown, context: string): void {
	expect(validate(value), `${context}\n${formatErrors(validate.errors)}`).toBe(true);
}

describe('Codex exec JSONL schema drift', () => {
	it('replays the pinned CLI stream through jsonlParser', () => {
		expect(events.map((event) => parseCodexEvent(event))).toEqual([
			{
				textParts: [],
				toolCall: null,
				usage: null,
				threadId: events[0].thread_id,
				error: undefined,
			},
			{ textParts: [], toolCall: null, usage: null, error: undefined },
			{
				textParts: ['schema fixture'],
				toolCall: null,
				usage: null,
				error: undefined,
			},
			{
				textParts: [],
				toolCall: null,
				usage: {
					inputTokens: 22058,
					outputTokens: 6,
					cachedTokens: 0,
					reasoningTokens: 0,
				},
				error: undefined,
			},
		]);
	});

	it('matches shared event and item models generated by the pinned CLI', () => {
		expect(events.map((event) => event.type)).toEqual([
			'thread.started',
			'turn.started',
			'item.completed',
			'turn.completed',
		]);

		for (const event of events) {
			switch (event.type) {
				case 'thread.started':
					expect(event).toEqual({
						type: 'thread.started',
						thread_id: expect.any(String),
					});
					break;
				case 'turn.started':
					expect(event).toEqual({ type: 'turn.started' });
					break;
				case 'item.completed': {
					const item = event.item as JsonRecord;
					expectSchemaMatch(
						validateThreadItem,
						{ ...item, type: item.type === 'agent_message' ? 'agentMessage' : item.type },
						'item.completed diverged from generated ThreadItem',
					);
					break;
				}
				case 'turn.completed': {
					const usage = event.usage as JsonRecord;
					expectSchemaMatch(
						validateUsage,
						{
							inputTokens: usage.input_tokens,
							cachedInputTokens: usage.cached_input_tokens,
							cacheWriteInputTokens: usage.cache_write_input_tokens,
							outputTokens: usage.output_tokens,
							reasoningOutputTokens: usage.reasoning_output_tokens,
							totalTokens: (usage.input_tokens as number) + (usage.output_tokens as number),
						},
						'turn.completed usage diverged from generated TokenUsageBreakdown',
					);
					break;
				}
				default:
					expect.fail(`Unrecognized Codex event type in fixture: ${String(event.type)}`);
			}
		}
	});
});
