name: Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy-webhooks:
    name: Deploy Webhooks
    runs-on: ubuntu-latest
    environment: CI
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --config fly.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-router:
    name: Deploy Router
    runs-on: ubuntu-latest
    environment: CI
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --config fly.router.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
